# This is a basic workflow to help you get started with Actions

name: Build and Publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main,dev,staging ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GCS_BUCKET_DEV: cmcd-web-sample-dev.realeyes.cloud
      GCS_BUCKET_STAGING: cmcd-web-sample-staging.realeyes.cloud
      GCS_BUCKET_PROD: cmcd-web-sample.realeyes.cloud

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm install -g @angular/cli > /dev/null

      - name: Build
        run: npm run build

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist

      - name: Authenticate Google Storage
        id: authenticate-google
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true 

      - name: Upload to gcs  
        if: github.ref == 'refs/heads/dev'
        id: upload-file-dev
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
          path: dist/
          destination: ${{ env.GCS_BUCKET_DEV }}         

      - name: Upload to gcs  
        if: github.ref == 'refs/heads/staging'
        id: upload-file-staging
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
          path: dist/
          destination: ${{ env.GCS_BUCKET_STAGING }}

      - name: Upload to gcs  
        if: github.ref == 'refs/heads/main'
        id: upload-file-prod
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
          path: dist/
          destination: ${{ env.GCS_BUCKET_PROD }}      